#!/bin/bash
#
#----------------------------------------------#
# Contributor: Tobias Holzmann                 #
# Last Change: April 2016                      #
# Topic:                                       #
# Email:       Tobias.Holzmann@Holzmann-cfd.de #
#----------------------------------------------#


#-------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear


#-------------------------------------------------------------------------------
rm -rf optimizationLog Log analyse*
rm -rf log* dakotaLog dakotaData* dakota.rst
rm -rf PyFoam* Ply*


#-------------------------------------------------------------------------------
